name: 'Terraform'

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  id-token: write  # Required for Workload Identity Federation

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Auth to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: 'projects/328527093228/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
        service_account: 'github-terraform@project-8f3b3c8e-4647-4878-8b5.iam.gserviceaccount.com'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3  # v3 is current, v1 is old

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false